<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

function envdata_init(){
  envdata_add_resource('chartist');
}

function envdata_cron(){
  module_load_include('inc', 'envdata', 'envdata.airq');
  envdata_airq_update_gov_file();
  envdata_airq_create_geojson();
}

function envdata_menu() {
  $items['envdata/chart/image/%'] = array(
    'title' => 'save chart svg to image',
    'page callback' => 'envdata_chart_image',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'envdata.chart.inc',
  );
  $items['envdata/chart/svg/%'] = array(
    'title' => 'render svg to html',
    'page callback' => 'envdata_chart_svg',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'envdata.chart.inc',
  );
  $items['envdata/csv/%/%'] = array(
    'title' => 'render svg to html',
    'page callback' => 'envdata_csv',
    'page arguments' => array(2, 3),
    'access arguments' => array('export envdata'),
    'type' => MENU_CALLBACK,
    'file' => 'envdata.csv.inc',
  );

  return $items;
}

function envdata_permission(){
  return array(
    'export envdata' => array(
      'title' => t('export envdata'),
      'description' => t('export csv and other format data from gcaa bigquery table'),
    ),
  );
}

function envdata_block_info() {
  $block['facility_realtime_charts'] = array(
    'info' => 'envdata: facility realtime charts',
    'cache' => DRUPAL_NO_CACHE,
  );
  $block['facility_realtime_charts_gov'] = array(
    'info' => 'envdata: facility realtime charts for gov',
    'cache' => DRUPAL_NO_CACHE,
  );

  return $block;
}

function envdata_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'facility_realtime_charts':
      module_load_include('inc', 'envdata', 'envdata.chart');
      if(arg(0) == 'facility' && arg(1) && empty(arg(2))){
        $vars = array(
          'registration_no' => arg(1),
          'path' => 'realtime/air/chimney_cache/{type}/' . arg(1) . '.csv',
        );
        $block['content'] = envdata_prepare_chart($vars);
      }
      break;
    case 'facility_realtime_charts_gov':
      module_load_include('inc', 'envdata', 'envdata.chart');
      if(arg(0) == 'facility' && arg(1) && arg(2) == 'gov'){
        $vars = array(
          'registration_no' => arg(1),
          'path' => 'realtime/air/chimney_cache_gov/{type}/' . arg(1) . '.csv',
        );
        $block['content'] = envdata_prepare_chart($vars);
      }
      break;
  }

  return $block;
}

function envdata_add_resource($type = 'all'){
  $module_envdata   = drupal_get_path('module', 'envdata');
  $js_option = array(
    'preprocess' => FALSE,
    'group' => 101,
  );

  if($type == 'chartist' || $type == 'all') {
    // chartist
    drupal_add_css($module_envdata . '/vendor/chartist/chartist.min.css');
    drupal_add_css($module_envdata . '/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css');
    drupal_add_js($module_envdata . '/vendor/chartist/chartist.min.js', array_merge(array('weight' => 1), $js_option));
    drupal_add_js($module_envdata . '/vendor/chartist-plugin-threshold/chartist-plugin-threshold.js', array_merge(array('weight' => 2), $js_option));
    drupal_add_js($module_envdata . '/vendor/chartist-plugin-axistitle/chartist-plugin-axistitle.min.js', array_merge(array('weight' => 3), $js_option));
    drupal_add_js($module_envdata . '/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.min.js', array_merge(array('weight' => 4), $js_option));
  }

  // papaparse
  if($type == 'papaparse' || $type == 'all') {
    drupal_add_js($module_envdata . '/vendor/papaparse/papaparse.min.js', $js_option);
  }

  // jquery-modal
  if($type == 'jquery-modal' || $type == 'all') {
    drupal_add_css($module_envdata . '/vendor/jquery-modal/jquery.modal.css');
    drupal_add_js($module_envdata . '/vendor/jquery-modal/jquery.modal.min.js', $js_option);
  }

  // tabslet
  if($type == 'tabslet' || $type == 'all') {
    drupal_add_js($module_envdata . '/vendor/tabslet/jquery.tabslet.min.js', $js_option);
  }

  // module custom
  if($type == 'envdata' || $type == 'all') {
    drupal_add_css($module_envdata . '/css/envdata-facility-charts.css');
    drupal_add_js($module_envdata . '/js/fbjs-init.js', $js_option);
    drupal_add_js($module_envdata . '/js/envdata-facility-charts.js', $js_option);
  }
}

function envdata_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'webform_client_form_54') {
    $not_found = FALSE;
    if(isset($_GET['registration_no']) && isset($_GET['report_picture'])){
      $no = strtolower($_GET['registration_no']);
      $name = db_select('factory', 'f')
        ->fields('f', array('facility_name'))
        ->condition('registration_no', $no, 'LIKE')
        ->execute()
        ->fetchField();
      if(!empty($name)) {
        $form['submitted']['registration_no']['#default_value'] = $_GET['registration_no'];
        $form['submitted']['registration_no']['#attributes']['readonly'] = 'readonly';
        $form['submitted']['registration_no']['#description'] = $name.'('.$_GET['registration_no'].')';
        $form['submitted']['report_picture']['#default_value'] = $_GET['report_picture'];
        $form['submitted']['report_picture']['#attributes']['readonly'] = 'readonly';
        $form['submitted']['report_picture']['#description'] = '<img src="'.$_GET['report_picture'].'" width="100%">';
      }
      else{
        $not_found = TRUE;
      }
    }
    else{
      $not_found = TRUE;
    }
    if ($not_found) {
      drupal_not_found();
      drupal_exit();
    }
  }
}
