<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

function envdata_cron(){
  module_load_include('inc', 'envdata', 'envdata.airq');
  envdata_airq_update_gov_file();
  envdata_airq_create_geojson();
}

function envdata_init() {
  $arg = arg();
  $current_path       = current_path();
  $current_path_alias = drupal_lookup_path('alias', $current_path);
  $module_envdata = drupal_get_path('module', 'envdata');

  if ($arg[0] == 'facility' && isset($arg[1])) {
    drupal_add_css($module_envdata . '/vendor/chartist/chartist.min.css');
    drupal_add_js($module_envdata . '/vendor/papaparse/papaparse.min.js');
    drupal_add_js($module_envdata . '/vendor/chartist/chartist.min.js');
    drupal_add_js($module_envdata . '/vendor/chartist-plugin-threshold/chartist-plugin-threshold.js');
    drupal_add_js($module_envdata . '/vendor/chartist-plugin-axistitle/chartist-plugin-axistitle.min.js');
  }
}

function envdata_block_info() {
  $block['facility_realtime_charts'] = array(
    'info' => 'envdata: facility realtime charts',
    'cache' => DRUPAL_NO_CACHE,
  );

  return $block;
}

function envdata_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'facility_realtime_charts':
      $block['content'] = _envdata_facility_realtime_charts_content();
      break;
  }

  return $block;
}

function _envdata_facility_realtime_charts_content() {
  global $base_url;
  $arg              = arg();
  $output           = '';
  $registration_no  = $arg[0] == 'facility' && isset($arg[1]) && !isset($arg[2]) ? $arg[1] : '';
  $data_url         = $registration_no ? $base_url . '/realtime/chimney_cache/1day/' . $registration_no . '.csv' : '';
  $csv_file_path    = $data_url ? $_SERVER['DOCUMENT_ROOT'] . '/realtime/chimney_cache/1day/' . $registration_no . '.csv' : '';
  $csv_exists       = file_exists($csv_file_path) ? TRUE : FALSE;
  $envdata_settings = array();
  $module_envdata   = drupal_get_path('module', 'envdata');

  // If csv url and file exist, init chartist
  if ($data_url && $csv_exists) {
    $output .= '<div id="charts"></div>';

    $envdata_settings['dataURL'] = $data_url;
    $envdata_settings['chartist_load'] = FALSE;
    drupal_add_css($module_envdata . '/css/envdata-facility-charts.css');
    drupal_add_js(array('envdata' => $envdata_settings), 'setting');    
    drupal_add_js($module_envdata . '/js/envdata-facility-charts.js');
  }

  return $output;
}
